version: '3.8'
services:
  mongodb:
    image: mongo:6
    container_name: tienda_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    command: ["--replSet", "rs0"]
  app:
    build: .
    container_name: tienda_app
    depends_on:
      - mongodb
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/tienda

volumes:
  mongo_data:
